# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='borad',
            new_name='board',
        ),
    ]
